package com.datascience.galc.dataGenerator;


import org.junit.Ignore;
import org.junit.Test;

/**
 * The class <code>TestDataGeneratorTest</code> contains tests for the class
 * {@link <code>TestDataGenerator</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 7/17/12 1:48 PM
 *
 * @author piotr.gnys@10clouds.com
 *
 * @version $Revision$
 */
public class SyntheticDataGeneratorTest {


	/**
	 * Run the ArrayList<String> generateCategoryNames(int) method test
	 */
	//@Ignore
	@Test
	public void testGeneratedSyntheticData() {
		final SyntheticDataGenerator dataGenerator = new SyntheticDataGenerator();
	}
}




/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = assertTrue = false callTestMethod = true createMain =
 * false createSetUp = false createTearDown = false createTestFixture = false
 * createTestStubs = false methods =
 * generateCategoryNames(I),generateTestObjects
 * (I!I),generateTestObjects(I!QMap<QString;QDouble;>;) package =
 * tests.dawidSkeneTester package.sourceFolder = LabelingTester/src
 * superclassType = junit.framework.TestCase testCase = TestDataGeneratorTest
 * testClassType = main.com.dawidSkeneTester.TestDataGenerator
 */
