package com.datascience.gal.quality;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;

import junit.framework.TestCase;

import org.junit.Ignore;

import com.datascience.gal.AssignedLabel;
import com.datascience.gal.Category;
import com.datascience.gal.CorrectLabel;
import com.datascience.gal.Datum;
import com.datascience.gal.DawidSkene;
import com.datascience.gal.IncrementalDawidSkene;

/**
 * The class <code>QualityEvaluationTest</code> contains tests for the class
 * {@link <code>AbstractDawidSkene</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 10/12/12 8:54 AM
 *
 * @author piotr.gnys@10clouds.com
 *
 * @version $Revision$
 */
public class QualityEvaluationTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public QualityEvaluationTest(String name) {
		super(name);
	}

	private void testData(DawidSkene ds) {
		ds.estimate(5);
		ClassificationCostEvaluator evaluator = new DS_MaxLikelihoodCostEvaluator();
		Map<String,Category> categoriesFromDs = ds.getCategories();
		Map<String,Datum> objects = ds.getObjects();
		Collection<String> categoryNames = categoriesFromDs.keySet();
		Collection<String> objectNames = objects.keySet();
		for (String objectName : objectNames) {
			for (String categoryName : categoryNames) {
				ds.computeProjectQuality(evaluator,categoryName,objectName);
			}
		}

		Map<String,Map<String,Double>> qualities = ds.getQualities();
		for (String objectName : objectNames) {
			for (String categoryName : categoryNames) {
				System.out.println("Object = "+objectName+" category = "+categoryName+" Quality = "+qualities.get(objectName).get(categoryName));
			}
		}
	}

	/**
	 * Run the void computeProjectQuality() method test
	 */
	public void testComputeProjectQuality() {
		Collection<Category> categories = new ArrayList<Category>();
		categories.add(new Category("Category1"));
		categories.add(new Category("Category2"));
		DawidSkene ds = new IncrementalDawidSkene("TestProject",categories);

		Collection<AssignedLabel> labels = new ArrayList<AssignedLabel>();
		//Worker1 quality is 100%
		labels.add(new AssignedLabel("Worker1","Object1","Category1"));
		labels.add(new AssignedLabel("Worker1","Object2","Category1"));
		labels.add(new AssignedLabel("Worker1","Object3","Category2"));
		labels.add(new AssignedLabel("Worker1","Object4","Category2"));
		//worker2
		labels.add(new AssignedLabel("Worker2","Object1","Category1"));
		labels.add(new AssignedLabel("Worker2","Object2","Category1"));
		labels.add(new AssignedLabel("Worker2","Object3","Category2"));
		labels.add(new AssignedLabel("Worker2","Object4","Category2"));
		//Worker3
		labels.add(new AssignedLabel("Worker3","Object1","Category1"));
		labels.add(new AssignedLabel("Worker3","Object2","Category1"));
		labels.add(new AssignedLabel("Worker3","Object3","Category2"));
		labels.add(new AssignedLabel("Worker3","Object4","Category2"));
		ds.addAssignedLabels(labels);

		Collection<CorrectLabel> evaluationData = new ArrayList<CorrectLabel>();
		evaluationData.add(new CorrectLabel("Object1","Category1"));
		evaluationData.add(new CorrectLabel("Object2","Category1"));
		evaluationData.add(new CorrectLabel("Object3","Category2"));
		evaluationData.add(new CorrectLabel("Object4","Category2"));
		ds.addEvaluationData(evaluationData);

		testData(ds);

	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames =
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = computeProjectQuality()
 * package = com.datascience.gal.quality
 * package.sourceFolder = DSaS/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = QualityEvaluationTest
 * testClassType = com.datascience.gal.AbstractDawidSkene
 */
